INSERT INTO modulo(criado_em, atualizado_em, carga_horaria, familia, modalidade, nome) VALUES 
					((select now()), (select now()), 16, 0, 0, "Digitação"),
					((select now()), (select now()), 17, 0, 0, "3D Studio I"),
					((select now()), (select now()), 17, 0, 0, "3D Studio II"),
					((select now()), (select now()), 17, 0, 0, "Access 2007"),
					((select now()), (select now()), 24, 9, 0, "Acucar Alcool I"),
					((select now()), (select now()), 24, 9, 0, "Acucar Alcool II"),
					((select now()), (select now()), 20, 9, 0, "Acucar Alcool III"),
					((select now()), (select now()), 20, 9, 0, "Acucar Alcool IV"),
					((select now()), (select now()), 17, 2, 0, "Assistente Administrativo 2017"),
					((select now()), (select now()), 16, 2, 0, "Assistente de Administração Financeira 2017"),
					((select now()), (select now()), 16, 2, 0, "Assistente de Departamento Pessoal 2017"),
					((select now()), (select now()), 16, 2, 0, "Assistente de Escrita Fiscal e Contabilidade 2017"),
					((select now()), (select now()), 16, 2, 0, "Assistente de Propaganda e Marketing 2017"),
					((select now()), (select now()), 24, 1, 0, "Atendente de Farmácia"),
					((select now()), (select now()), 16, 2, 0, "Atendimento Nota 1000"),
					((select now()), (select now()), 20, 0, 0, "AutoCad 2D 2013"),
					((select now()), (select now()), 20, 0, 0, "AutoCad 3D 2013"),
					((select now()), (select now()), 16, 1, 0, "Auxiliar Médico"),
					((select now()), (select now()), 16, 1, 0, "Auxiliar Odontológico"),
					((select now()), (select now()), 16, 2, 0, "Cobrança"),
					((select now()), (select now()), 16, 2, 0, "Compras e Estoque"),
					((select now()), (select now()), 16, 0, 0, "CorelDraw X6"),
					((select now()), (select now()), 16, 2, 0, "Credito"),
					((select now()), (select now()), 16, 2, 0, "Custos"),
					((select now()), (select now()), 80, 0, 0, "Desenvolvimento de Aplicativos"),
					((select now()), (select now()), 70, 0, 0, "Desenvolvimento de Aplicativos Avançado"),
					((select now()), (select now()), 80, 0, 0, "Desenvolvimento de Games"),
					((select now()), (select now()), 70, 0, 0, "Desenvolvimento de Games Avançado"),
					((select now()), (select now()), 16, 0, 0, "Dreamweaver CS6"),
					((select now()), (select now()), 16, 0, 0, "Edição de Video Adobe Premiere Pro CS6"),
					((select now()), (select now()), 96, 3, 0, "English Course Book 1"),
					((select now()), (select now()), 96, 3, 0, "English Course Book 2"),
					((select now()), (select now()), 96, 3, 0, "English Course Book 3"),
					((select now()), (select now()), 96, 3, 0, "English Course Book 4"),
					((select now()), (select now()), 16, 0, 0, "Excel 2013"),
					((select now()), (select now()), 16, 0, 0, "Excel Avançado I 2013"),
					((select now()), (select now()), 16, 0, 0, "Excel Avançado II 2013"),
					((select now()), (select now()), 16, 0, 0, "Fireworks CS6"),
					((select now()), (select now()), 16, 0, 0, "Flash CS6"),
					((select now()), (select now()), 8, 0, 0, "FrontPage 2013"),
					((select now()), (select now()), 17, 0, 0, "Google e Redes Sociais"),
					((select now()), (select now()), 16, 2, 0, "Hotelaria"),
					((select now()), (select now()), 10, 0, 0, "HTML 2013"),
					((select now()), (select now()), 16, 0, 0, "Indesign CS6"),
					((select now()), (select now()), 18, 0, 0, "Informática para Concurso - Office"),
					((select now()), (select now()), 18, 0, 0, "Informática para Concurso - Sistemas Operacionais"),
					((select now()), (select now()), 16, 0, 0, "Internet com Oulook 2019"),
					((select now()), (select now()), 16, 0, 0, "Java I"),
					((select now()), (select now()), 14, 0, 0, "Java II"),
					((select now()), (select now()), 16, 2, 0, "Liderança"),
					((select now()), (select now()), 17, 0, 0, "Linguaguem de  Programação - Delphi I"),
					((select now()), (select now()), 15, 0, 0, "Linguaguem de Programação - Delphi II"),
					((select now()), (select now()), 16, 0, 0, "Lógica de Programaçao"),
					((select now()), (select now()), 32, 0, 0, "Manutenção de Celular"),
					((select now()), (select now()), 24, 0, 0, "Manutenção de Notebook"),
					((select now()), (select now()), 16, 2, 0, "Matematica Financeira 2017"),
					((select now()), (select now()), 40, 0, 0, "Montagem e Manutenção"),
					((select now()), (select now()), 16, 2, 0, "Operador de Caixa 2017"),
					((select now()), (select now()), 18, 9, 0, "Petróleo e Gás Novo I"),
					((select now()), (select now()), 18, 9, 0, "Petróleo e Gás Novo II"),
					((select now()), (select now()), 18, 9, 0, "Petróleo e Gás Novo III"),
					((select now()), (select now()), 18, 9, 0, "Petróleo e Gás Novo IV"),
					((select now()), (select now()), 16, 0, 0, "Photoshop CS6"),
					((select now()), (select now()), 24, 0, 0, "PHP"),
					((select now()), (select now()), 16, 0, 0, "PowePoint 2019"),
					((select now()), (select now()), 96, 6, 0, "Preparatório ENEM 2017"),
					((select now()), (select now()), 20, 0, 0, "Redes"),
					((select now()), (select now()), 16, 0, 0, "Robótica I -Mecânica e Eletrônica"),
					((select now()), (select now()), 16, 0, 0, "Robótica II - Lógica de Programação"),
					((select now()), (select now()), 16, 0, 0, "Robótica III - Automação"),
					((select now()), (select now()), 24, 0, 0, "Robótica IV - Competição"),
					((select now()), (select now()), 24, 0, 0, "Robótica V - Arduíno com IOT"),
					((select now()), (select now()), 16, 2, 0, "Secretariado 2017"),
					((select now()), (select now()), 16, 1, 0, "Técnicas de Recepção"),
					((select now()), (select now()), 14, 2, 0, "Telemarketing Mod 1"),
					((select now()), (select now()), 14, 2, 0, "Telemarketing Mod 2"),
					((select now()), (select now()), 16, 2, 0, "Turismo 2"),
					((select now()), (select now()), 16, 2, 0, "Vendas"),
					((select now()), (select now()), 10, 0, 0, "Visual Basic I"),
					((select now()), (select now()), 12, 0, 0, "Visual Basic II"),
					((select now()), (select now()), 12, 0, 0, "Windows 10"),
					((select now()), (select now()), 16, 0, 0, "Word 2019"),
					((select now()), (select now()), 18, 0, 0, "Youtuber"),
					((select now()), (select now()), 8, 0, 0, "Introdução à Informática"),
					((select now()), (select now()), 14, 0, 0, "Excel 2019 Essencial"),
					((select now()), (select now()), 30, 2, 1, "Abertura de Empresas"),
					((select now()), (select now()), 20, 2, 1, "Administração de Materiais"),
					((select now()), (select now()), 60, 2, 1, "Análise de Crédito, Financiamento e Investimento"),
					((select now()), (select now()), 80, 2, 1, "Análise de Desempenho"),
					((select now()), (select now()), 40, 2, 1, "Arquitetura e Urbanismo para Corretores de Imóveis"),
					((select now()), (select now()), 60, 2, 1, "Avaliação Imobiliária"),
					((select now()), (select now()), 60, 2, 1, "Cerimonial e Protocolo"),
					((select now()), (select now()), 30, 2, 1, "Compras"),
					((select now()), (select now()), 60, 2, 1, "Comunicação e Informação"),
					((select now()), (select now()), 40, 2, 1, "Contabilidade de Custos"),
					((select now()), (select now()), 40, 2, 1, "Contabilidade Pública"),
					((select now()), (select now()), 20, 2, 1, "Controle Patrimonial"),
					((select now()), (select now()), 40, 2, 1, "Custos Logísticos"),
					((select now()), (select now()), 40, 2, 1, "Departamento de Pessoal"),
					((select now()), (select now()), 40, 2, 1, "Desenho Técnico"),
					((select now()), (select now()), 30, 2, 1, "Direito Ambiental"),
					((select now()), (select now()), 30, 2, 1, "Direito do Consumidor"),
					((select now()), (select now()), 30, 2, 1, "Direito Trabalhista"),
					((select now()), (select now()), 20, 2, 1, "Empreendedorismo"),
					((select now()), (select now()), 60, 2, 1, "Escrita Fiscal e Tributos"),
					((select now()), (select now()), 60, 2, 1, "Espanhol Instrumental Avançado"),
					((select now()), (select now()), 40, 2, 1, "Estatística"),
					((select now()), (select now()), 20, 2, 1, "Ética e Cidadania"),
					((select now()), (select now()), 30, 2, 1, "Fundamentos da Economia"),
					((select now()), (select now()), 50, 2, 1, "Fundamentos do Trabalho"),
					((select now()), (select now()), 20, 2, 1, "Gerenciador de Dados"),
					((select now()), (select now()), 30, 2, 1, "Gerenciamento de Projetos"),
					((select now()), (select now()), 30, 2, 1, "Gestão da Qualidade"),
					((select now()), (select now()), 20, 2, 1, "Gestão de Carreira"),
					((select now()), (select now()), 20, 2, 1, "Gestão de Contratos"),
					((select now()), (select now()), 60, 2, 1, "Gestão de Eventos"),
					((select now()), (select now()), 30, 2, 1, "Gestão de Recursos Humanos"),
					((select now()), (select now()), 20, 2, 1, "Gestão do Marketing"),
					((select now()), (select now()), 30, 2, 1, "Gestão Financeira"),
					((select now()), (select now()), 30, 2, 1, "Inglês Instrumental"),
					((select now()), (select now()), 60, 2, 1, "Inglês Instrumental Avançado"),
					((select now()), (select now()), 20, 2, 1, "Introdução a Gestão de Processos"),
					((select now()), (select now()), 40, 2, 1, "Licenciamento e Direito Imobiliário"),
					((select now()), (select now()), 30, 2, 1, "Logística"),
					((select now()), (select now()), 80, 2, 1, "Logística de Armazenagem"),
					((select now()), (select now()), 40, 2, 1, "Marketing Imobiliário"),
					((select now()), (select now()), 20, 2, 1, "Marketing Pessoal"),
					((select now()), (select now()), 30, 2, 1, "Matemática Financeira"),
					((select now()), (select now()), 40, 2, 1, "Mercado Financeiro"),
					((select now()), (select now()), 60, 2, 1, "Mercado Imobiliário"),
					((select now()), (select now()), 70, 2, 1, "Operações Imobiliárias"),
					((select now()), (select now()), 60, 2, 1, "Planejamento e Análise de Postos de Trabalho"),
					((select now()), (select now()), 20, 2, 1, "Planejamento Estratégico"),
					((select now()), (select now()), 30, 2, 1, "Português Instrumental"),
					((select now()), (select now()), 10, 2, 1, "Processos de Aprendizagem"),
					((select now()), (select now()), 30, 2, 1, "Psicologia do Trabalho"),
					((select now()), (select now()), 80, 2, 1, "Recrutamento e Seleção"),
					((select now()), (select now()), 20, 2, 1, "Responsabilidade Socioambiental"),
					((select now()), (select now()), 20, 2, 1, "Rotinas Bancárias"),
					((select now()), (select now()), 60, 2, 1, "Rotinas Contábeis"),
					((select now()), (select now()), 20, 2, 1, "Rotinas Jurídicas nas Empresas"),
					((select now()), (select now()), 30, 2, 1, "Sistema de Gestão Empresarial"),
					((select now()), (select now()), 40, 2, 1, "Sistemas de Informações Gerenciais"),
					((select now()), (select now()), 60, 2, 1, "Técnicas de Atendimento"),
					((select now()), (select now()), 40, 2, 1, "Técnicas de Recepção, Atendimento e Cobrança"),
					((select now()), (select now()), 20, 2, 1, "Técnicas de Treinamento"),
					((select now()), (select now()), 30, 2, 1, "Técnicas de Vendas"),
					((select now()), (select now()), 60, 2, 1, "Transações Financeiras para o Mercado Imobiliário"),
					((select now()), (select now()), 60, 2, 1, "Treinamento e Desenvolvimento"),
					((select now()), (select now()), 80, 2, 1, "Informática e Gerenciador de Dados"),
					((select now()), (select now()), 80, 2, 1, "Contabilidade e Finanças"),
					((select now()), (select now()), 80, 2, 1, "Gestão de Pessoas "),
					((select now()), (select now()), 80, 2, 1, "Matemática Financeira e Estatística"),
					((select now()), (select now()), 80, 2, 1, "Organização Empresarial"),
					((select now()), (select now()), 120, 2, 1, "Comunicação e Marketing"),
					((select now()), (select now()), 120, 2, 1, "Técnicas de Negociação e Vendas"),
					((select now()), (select now()), 90, 2, 1, "Gerenciamento de Projetos e Eventos"),
					((select now()), (select now()), 90, 2, 1, "Empreendedorismo e Gestão Empresarial"),
					((select now()), (select now()), 100, 2, 1, "Qualidade e Segurança"),
					((select now()), (select now()), 80, 2, 1, "Direito e Fundamentos do Trabalho"),
					((select now()), (select now()), 80, 2, 1, "Gestão Financeira e Planejamento Estratégico"),
					((select now()), (select now()), 110, 2, 1, "Gestão de Estoques e Armazenagem"),
					((select now()), (select now()), 140, 2, 1, "Desenvolvimento e análise de cargos e desempenho"),
					((select now()), (select now()), 160, 2, 1, "T&D, recrutamento e seleção"),
					((select now()), (select now()), 80, 2, 1, "Gestão da Carreira Profissional e Pessoal"),
					((select now()), (select now()), 80, 2, 1, "Saúde e Segurança no trabalho"),
					((select now()), (select now()), 80, 2, 1, "Marketing e Direito Imobiliário"),
					((select now()), (select now()), 90, 2, 1, "Planejamento de Eventos Promocionais"),
					((select now()), (select now()), 130, 2, 1, "Transações Imobiliárias "),
					((select now()), (select now()), 100, 2, 1, "Análise de Ativos imobiliários"),
					((select now()), (select now()), 40, 1, 1, "Atendimento Pré-Hospitalar"),
					((select now()), (select now()), 30, 1, 1, "Farmacologia"),
					((select now()), (select now()), 30, 1, 1, "Microbiologia e Imunologia"),
					((select now()), (select now()), 40, 1, 1, "Saúde Coletiva"),
					((select now()), (select now()), 70, 5, 1, "Auxiliar de Limpeza Urbana"),
					((select now()), (select now()), 40, 5, 1, "Materiais de Construção"),
					((select now()), (select now()), 60, 7, 1, "Avaliação e Análise de Impactos Ambientais"),
					((select now()), (select now()), 40, 7, 1, "Ecologia"),
					((select now()), (select now()), 40, 7, 1, "Gestão da Qualidade do Ar"),
					((select now()), (select now()), 40, 7, 1, "Gestão de Resíduos Sólidos"),
					((select now()), (select now()), 30, 7, 1, "Recuperação de Áreas Degradadas"),
					((select now()), (select now()), 60, 7, 1, "Tratamento de Água e Efluentes"),
					((select now()), (select now()), 30, 8, 1, "Comissão Interna de Prevenção de Acidentes (CIPA)"),
					((select now()), (select now()), 20, 8, 1, "Equipamentos de Proteção Individual (EPI)"),
					((select now()), (select now()), 20, 8, 1, "Inspeções de Segurança"),
					((select now()), (select now()), 60, 8, 1, "Segurança do Trabalho na Construção Civil (NR-18)"),
					((select now()), (select now()), 50, 8, 1, "Segurança em Serviços com Eletricidade (NR-10)"),
					((select now()), (select now()), 30, 0, 1, "Informática Básica e Mobilidade"),
					((select now()), (select now()), 80, 0, 1, "Lógica de Programação"),
					((select now()), (select now()), 30, 0, 1, "Planilha Eletrônica Avançada"),
					((select now()), (select now()), 80, 0, 1, "Redes de Computadores"),
					((select now()), (select now()), 80, 4, 1, "Organização e Funcionamento do Sistema Educacional Brasileiro"),
					((select now()), (select now()), 60, 4, 1, "Língua Brasileira de Sinais - LIBRAS"),
					((select now()), (select now()), 80, 4, 1, "Secretarias Acadêmicas Digitais"),
					((select now()), (select now()), 80, 4, 1, "Técnicas Secretariais");

INSERT INTO apostila(criado_em, atualizado_em, duracao_em_mes, nome, valor_compra, valor_venda, modulo_id) VALUES 
					((select now()), (select now()), 2, "Apostila de 3D Studio I", 0, 60, (select m.id from modulo m where m.nome = "3D Studio I" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de 3D Studio II", 0, 60, (select m.id from modulo m where m.nome = "3D Studio II" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Access 2007", 0, 60, (select m.id from modulo m where m.nome = "Access 2007" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Açúcar e Álcool I", 0, 60, (select m.id from modulo m where m.nome = "Acucar Alcool I" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Açúcar e Álcool II", 0, 60, (select m.id from modulo m where m.nome = "Acucar Alcool II" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Açúcar e Álcool III", 0, 60, (select m.id from modulo m where m.nome = "Acucar Alcool III" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Açúcar e Álcool IV", 0, 60, (select m.id from modulo m where m.nome = "Acucar Alcool IV" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Assistente Administrativo", 0, 60, (select m.id from modulo m where m.nome = "Assistente Administrativo 2017" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Assistente de Administração Financeira", 0, 60, (select m.id from modulo m where m.nome = "Assistente de Administração Financeira 2017" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Assistente de Departamento Pessoal", 0, 60, (select m.id from modulo m where m.nome = "Assistente de Departamento Pessoal 2017" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Assistente de escrita fiscal e Contabilidade", 0, 60, (select m.id from modulo m where m.nome = "Assistente de Escrita Fiscal e Contabilidade 2017" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Assistente de Propaganda & Marketing", 0, 60, (select m.id from modulo m where m.nome = "Assistente de Propaganda e Marketing 2017" and m.modalidade = 0)),
					((select now()), (select now()), 3, "Apostila de Atendente de Farmácia", 0, 60, (select m.id from modulo m where m.nome = "Atendente de Farmácia" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Atendimento ao Cliente Nota 1.000", 0, 60, (select m.id from modulo m where m.nome = "Atendimento Nota 1000" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Autocad 2D", 0, 60, (select m.id from modulo m where m.nome = "AutoCad 2D 2013" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Autocad 3D", 0, 60, (select m.id from modulo m where m.nome = "AutoCad 3D 2013" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Auxiliar Médico", 0, 60, (select m.id from modulo m where m.nome = "Auxiliar Médico" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Auxiliar Odontológico", 0, 60, (select m.id from modulo m where m.nome = "Auxiliar Odontológico" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Cobrança", 0, 60, (select m.id from modulo m where m.nome = "Cobrança" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Compras e Estoque", 0, 60, (select m.id from modulo m where m.nome = "Compras e Estoque" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Corel Draw X6", 0, 60, (select m.id from modulo m where m.nome = "CorelDraw X6" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Crédito", 0, 60, (select m.id from modulo m where m.nome = "Credito" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Custos", 0, 60, (select m.id from modulo m where m.nome = "Custos" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Desenvolvimento de APP", 0, 200, (select m.id from modulo m where m.nome = "Desenvolvimento de Aplicativos" and m.modalidade = 0)),
					((select now()), (select now()), 2, "LIVRO APLICATIVOS AVANÇADO - MODULO I", 0, 130, (select m.id from modulo m where m.nome = "Desenvolvimento de Aplicativos Avançado" and m.modalidade = 0)),
					((select now()), (select now()), 2, "LIVRO APLICATIVOS AVANÇADO - MODULO II", 0, 130, (select m.id from modulo m where m.nome = "Desenvolvimento de Aplicativos Avançado" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Desenvolvimento de Games", 0, 200, (select m.id from modulo m where m.nome = "Desenvolvimento de Games" and m.modalidade = 0)),
					((select now()), (select now()), 2, "LIVRO GAMES AVANÇADO - MÓDULO I", 0, 130, (select m.id from modulo m where m.nome = "Desenvolvimento de Games Avançado" and m.modalidade = 0)),
					((select now()), (select now()), 2, "LIVRO GAMES AVANÇADO - MÓDULO II", 0, 130, (select m.id from modulo m where m.nome = "Desenvolvimento de Games Avançado" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Dreamweaver CS6", 0, 60, (select m.id from modulo m where m.nome = "Dreamweaver CS6" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Edição de Vídeo", 0, 60, (select m.id from modulo m where m.nome = "Edição de Video Adobe Premiere Pro CS6" and m.modalidade = 0)),
					((select now()), (select now()), 12, "KIT ALUNO INGLES ANUAL BOOK 1", 0, 450, (select m.id from modulo m where m.nome = "English Course Book 1" and m.modalidade = 0)),
					((select now()), (select now()), 12, "KIT ALUNO INGLES ANUAL BOOK 2", 0, 450, (select m.id from modulo m where m.nome = "English Course Book 2" and m.modalidade = 0)),
					((select now()), (select now()), 12, "KIT ALUNO INGLES ANUAL BOOK 3", 0, 450, (select m.id from modulo m where m.nome = "English Course Book 3" and m.modalidade = 0)),
					((select now()), (select now()), 12, "KIT ALUNO INGLES ANUAL BOOK 4", 0, 450, (select m.id from modulo m where m.nome = "English Course Book 4" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Excel 2013", 0, 60, (select m.id from modulo m where m.nome = "Excel 2013" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Excel Avançado I 2013", 0, 60, (select m.id from modulo m where m.nome = "Excel Avançado I 2013" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Excel Avançado II 2013", 0, 60, (select m.id from modulo m where m.nome = "Excel Avançado II 2013" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Fireworks CS6", 0, 60, (select m.id from modulo m where m.nome = "Fireworks CS6" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Flash CS6", 0, 60, (select m.id from modulo m where m.nome = "Flash CS6" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de FrontPage", 0, 60, (select m.id from modulo m where m.nome = "FrontPage 2013" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Google e Redes Sociais", 0, 60, (select m.id from modulo m where m.nome = "Google e Redes Sociais" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Hotelaria 2013", 0, 60, (select m.id from modulo m where m.nome = "Hotelaria" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de HTML 2013", 0, 60, (select m.id from modulo m where m.nome = "HTML 2013" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Indesign CS6", 0, 60, (select m.id from modulo m where m.nome = "Indesign CS6" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Informática para Concurso - Office", 0, 60, (select m.id from modulo m where m.nome = "Informática para Concurso - Office" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Informática para Concursos - Sistema Operacional", 0, 60, (select m.id from modulo m where m.nome = "Informática para Concurso - Sistemas Operacionais" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Internet 2015", 0, 60, (select m.id from modulo m where m.nome = "Internet com Oulook 2019" and m.modalidade = 0)),
					((select now()), (select now()), 2, "APOSTILA INTERNET E OUTLOOK 2019", 29.9, 60, (select m.id from modulo m where m.nome = "Internet com Oulook 2019" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Java I", 0, 60, (select m.id from modulo m where m.nome = "Java I" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Java II", 0, 60, (select m.id from modulo m where m.nome = "Java II" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Liderança", 0, 60, (select m.id from modulo m where m.nome = "Liderança" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Delphi I", 0, 60, (select m.id from modulo m where m.nome = "Linguaguem de  Programação - Delphi I" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Delphi II", 0, 60, (select m.id from modulo m where m.nome = "Linguaguem de Programação - Delphi II" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Lógica de Programação", 0, 60, (select m.id from modulo m where m.nome = "Lógica de Programaçao" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Manutenção de Celular", 0, 60, (select m.id from modulo m where m.nome = "Manutenção de Celular" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Manutenção de Notebook", 0, 60, (select m.id from modulo m where m.nome = "Manutenção de Notebook" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Matematica Financeira 2017", 0, 60, (select m.id from modulo m where m.nome = "Matematica Financeira 2017" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Montagem e Manutenção I", 0, 60, (select m.id from modulo m where m.nome = "Montagem e Manutenção" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Montagem e Manutenção II", 0, 60, (select m.id from modulo m where m.nome = "Montagem e Manutenção" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Operador de Caixa 2017", 0, 60, (select m.id from modulo m where m.nome = "Operador de Caixa 2017" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Petróleo e Gás I", 0, 60, (select m.id from modulo m where m.nome = "Petróleo e Gás Novo I" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Petróleo e Gás II", 0, 60, (select m.id from modulo m where m.nome = "Petróleo e Gás Novo II" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Petróleo e Gás III", 0, 60, (select m.id from modulo m where m.nome = "Petróleo e Gás Novo III" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Petróleo e Gás IV", 0, 60, (select m.id from modulo m where m.nome = "Petróleo e Gás Novo IV" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Photoshop CS6", 0, 60, (select m.id from modulo m where m.nome = "Photoshop CS6" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de PHP", 0, 60, (select m.id from modulo m where m.nome = "PHP" and m.modalidade = 0)),
					((select now()), (select now()), 2, "APOSTILA POWER POINT 2019", 29.9, 60, (select m.id from modulo m where m.nome = "PowePoint 2019" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Livro Enem 2017", 0, 300, (select m.id from modulo m where m.nome = "Preparatório ENEM 2017" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Redes", 0, 60, (select m.id from modulo m where m.nome = "Redes" and m.modalidade = 0)),
					((select now()), (select now()), 2, "LIVRO ROBOTICA 1 - MECANICA E ELETRONICA", 0, 130, (select m.id from modulo m where m.nome = "Robótica I -Mecânica e Eletrônica" and m.modalidade = 0)),
					((select now()), (select now()), 2, "LIVRO ROBOTICA 2 - LÓGICA DE PROGRAMAÇÃO", 0, 130, (select m.id from modulo m where m.nome = "Robótica II - Lógica de Programação" and m.modalidade = 0)),
					((select now()), (select now()), 2, "LIVRO ROBOTICA 3 - AUTOMAÇÂO", 0, 130, (select m.id from modulo m where m.nome = "Robótica III - Automação" and m.modalidade = 0)),
					((select now()), (select now()), 2, "LIVRO ROBOTICA 4 - COMPETIÇÃO", 0, 130, (select m.id from modulo m where m.nome = "Robótica IV - Competição" and m.modalidade = 0)),
					((select now()), (select now()), 2, "LIVRO ROBOTICA 5 - ARDUÍNO COM IOT", 0, 130, (select m.id from modulo m where m.nome = "Robótica V - Arduíno com IOT" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Secretariado 2017", 0, 60, (select m.id from modulo m where m.nome = "Secretariado 2017" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Tecnicas de Recepção", 0, 60, (select m.id from modulo m where m.nome = "Técnicas de Recepção" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Telemarketing I", 0, 60, (select m.id from modulo m where m.nome = "Telemarketing Mod 1" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Telemarketing II", 0, 60, (select m.id from modulo m where m.nome = "Telemarketing Mod 2" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Turismo 2013", 0, 60, (select m.id from modulo m where m.nome = "Turismo 2" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Vendas", 0, 60, (select m.id from modulo m where m.nome = "Vendas" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Visual basic I", 0, 60, (select m.id from modulo m where m.nome = "Visual Basic I" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Visual basic II", 0, 60, (select m.id from modulo m where m.nome = "Visual Basic II" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Windows 10", 29.9, 60, (select m.id from modulo m where m.nome = "Windows 10" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Word 2019", 29.9, 60, (select m.id from modulo m where m.nome = "Word 2019" and m.modalidade = 0)),
					((select now()), (select now()), 2, "Apostila de Youtuber", 0, 60, (select m.id from modulo m where m.nome = "Youtuber" and m.modalidade = 0)),
					((select now()), (select now()), 1, "APOSTILA INTRODUÇÃO A INFORMATICA 2019", 29.9, 60, (select m.id from modulo m where m.nome = "Introdução à Informática" and m.modalidade = 0)),
					((select now()), (select now()), 2, "APOSTILA EXCEL ESSENCIAL 2019", 29.9, 60, (select m.id from modulo m where m.nome = "Excel 2019 Essencial" and m.modalidade = 0));


INSERT INTO curso (criado_em, atualizado_em, nome) VALUES 
					((select now()), (select now()), "Programador"),
					((select now()), (select now()), "PersonalCAD"),
					((select now()), (select now()), "Açúcar e Álcool"),
					((select now()), (select now()), "Personalizado"),
					((select now()), (select now()), "Montagem e Manutenção"),
					((select now()), (select now()), "Atendimento e Vendas"),
					((select now()), (select now()), "Google e Redes Sociais"),
					((select now()), (select now()), "Administração Contábil"),
					((select now()), (select now()), "Administração em Vendas"),
					((select now()), (select now()), "Profissional da Saúde"),
					((select now()), (select now()), "Informática para Concursos"),
					((select now()), (select now()), "Turismo e Hotelaria 2013"),
					((select now()), (select now()), "Gestão Financeira"),
					((select now()), (select now()), "Petróleo e Gás 2013"),
					((select now()), (select now()), "Operador de Computador 2019"),
					((select now()), (select now()), "Analista de TI e Sistemas"),
					((select now()), (select now()), "Desenvolvedor de Sistemas e Web"),
					((select now()), (select now()), "Informática Master "),
					((select now()), (select now()), "Web Designer 2016"),
					((select now()), (select now()), "Analista Financeiro"),
					((select now()), (select now()), "Gestor de Marketing e Vendas 2017"),
					((select now()), (select now()), "Atendente de Clínincas e Laboratórios 2017"),
					((select now()), (select now()), "Atendente de Farmácia 2017"),
					((select now()), (select now()), "Desenvolvedor de Games e Apps"),
					((select now()), (select now()), "Gestor Administrativo 2017"),
					((select now()), (select now()), "Primeiro Emprego"),
					((select now()), (select now()), "Supervisor Hoteleiro"),
					((select now()), (select now()), "Supervisor de Atendimento e CallCenter 2017"),
					((select now()), (select now()), "Analista de Recursos Humanos 2017"),
					((select now()), (select now()), "Secretariado Executivo"),
					((select now()), (select now()), "Designer Gráfico 2017"),
					((select now()), (select now()), "Operador de Caixa 2017"),
					((select now()), (select now()), "Desenvolvedor de games"),
					((select now()), (select now()), "Desenvolvedor de aplicativos"),
					((select now()), (select now()), "Youtuber"),
					((select now()), (select now()), "Rotinas Administrativas"),
					((select now()), (select now()), "Excel Avançado 2013"),
					((select now()), (select now()), "Preparatório para ENEM"),
					((select now()), (select now()), "Desenvolvimento de Aplicativos Avançados"),
					((select now()), (select now()), "Desenvolvimento de Games Avançado"),
					((select now()), (select now()), "English Course Book"),
					((select now()), (select now()), "Robótica Inventor"),
					((select now()), (select now()), "Designer Gráfico e Digital");

INSERT INTO curso_modulo(curso_id, modulo_id) VALUES
						((SELECT c.Id FROM curso c WHERE c.Nome = "Programador"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Access 2007" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Programador"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Java I" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Programador"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Java II" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Programador"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Linguaguem de  Programação - Delphi I" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Programador"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Linguaguem de Programação - Delphi II" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Programador"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Lógica de Programaçao" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Programador"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Visual Basic I" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Programador"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Visual Basic II" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "PersonalCAD"), (SELECT m.Id FROM modulo m WHERE m.Nome = "3D Studio I" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "PersonalCAD"), (SELECT m.Id FROM modulo m WHERE m.Nome = "3D Studio II" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "PersonalCAD"), (SELECT m.Id FROM modulo m WHERE m.Nome = "AutoCad 2D 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "PersonalCAD"), (SELECT m.Id FROM modulo m WHERE m.Nome = "AutoCad 3D 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Açúcar e Álcool"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Acucar Alcool I" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Açúcar e Álcool"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Acucar Alcool II" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Açúcar e Álcool"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Acucar Alcool III" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Açúcar e Álcool"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Acucar Alcool IV" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Montagem e Manutenção"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Manutenção de Celular" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Montagem e Manutenção"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Manutenção de Notebook" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Montagem e Manutenção"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Montagem e Manutenção" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Montagem e Manutenção"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Redes" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendimento e Vendas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Atendimento Nota 1000" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendimento e Vendas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Telemarketing Mod 1" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendimento e Vendas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Telemarketing Mod 2" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendimento e Vendas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Vendas" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Google e Redes Sociais"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Google e Redes Sociais" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Google e Redes Sociais"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Internet com Oulook 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Administração Contábil"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente Administrativo 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Administração Contábil"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Administração Financeira 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Administração Contábil"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Escrita Fiscal e Contabilidade 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Administração Contábil"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Administração Contábil"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel Avançado I 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Administração Contábil"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel Avançado II 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Administração Contábil"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Matematica Financeira 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Administração em Vendas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Atendimento Nota 1000" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Administração em Vendas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Administração em Vendas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "PowePoint 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Administração em Vendas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Telemarketing Mod 1" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Administração em Vendas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Telemarketing Mod 2" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Administração em Vendas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Vendas" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Profissional da Saúde"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Atendente de Farmácia" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Profissional da Saúde"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Auxiliar Médico" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Profissional da Saúde"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Auxiliar Odontológico" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Profissional da Saúde"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Técnicas de Recepção" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Informática para Concursos"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Informática para Concurso - Office" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Informática para Concursos"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Informática para Concurso - Sistemas Operacionais" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Turismo e Hotelaria 2013"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Hotelaria" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Turismo e Hotelaria 2013"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Turismo 2" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestão Financeira"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Administração Financeira 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestão Financeira"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Cobrança" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestão Financeira"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Compras e Estoque" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestão Financeira"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Credito" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestão Financeira"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Custos" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestão Financeira"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Liderança" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Petróleo e Gás 2013"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Petróleo e Gás Novo I" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Petróleo e Gás 2013"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Petróleo e Gás Novo II" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Petróleo e Gás 2013"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Petróleo e Gás Novo III" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Petróleo e Gás 2013"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Petróleo e Gás Novo IV" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Operador de Computador 2019"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Internet com Oulook 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Operador de Computador 2019"), (SELECT m.Id FROM modulo m WHERE m.Nome = "PowePoint 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Operador de Computador 2019"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Windows 10" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Operador de Computador 2019"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Word 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Operador de Computador 2019"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Introdução à Informática" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Operador de Computador 2019"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel 2019 Essencial" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de TI e Sistemas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Access 2007" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de TI e Sistemas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Java I" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de TI e Sistemas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Java II" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de TI e Sistemas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Linguaguem de  Programação - Delphi I" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de TI e Sistemas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Linguaguem de Programação - Delphi II" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de TI e Sistemas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Lógica de Programaçao" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de TI e Sistemas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Manutenção de Celular" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de TI e Sistemas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Manutenção de Notebook" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de TI e Sistemas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Montagem e Manutenção" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de TI e Sistemas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Redes" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de TI e Sistemas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Visual Basic I" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de TI e Sistemas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Visual Basic II" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Desenvolvedor de Sistemas e Web"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Access 2007" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Desenvolvedor de Sistemas e Web"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Dreamweaver CS6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Desenvolvedor de Sistemas e Web"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Fireworks CS6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Desenvolvedor de Sistemas e Web"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Flash CS6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Desenvolvedor de Sistemas e Web"), (SELECT m.Id FROM modulo m WHERE m.Nome = "FrontPage 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Desenvolvedor de Sistemas e Web"), (SELECT m.Id FROM modulo m WHERE m.Nome = "HTML 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Desenvolvedor de Sistemas e Web"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Java I" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Desenvolvedor de Sistemas e Web"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Java II" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Desenvolvedor de Sistemas e Web"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Linguaguem de  Programação - Delphi I" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Desenvolvedor de Sistemas e Web"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Linguaguem de Programação - Delphi II" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Desenvolvedor de Sistemas e Web"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Lógica de Programaçao" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Desenvolvedor de Sistemas e Web"), (SELECT m.Id FROM modulo m WHERE m.Nome = "PHP" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Desenvolvedor de Sistemas e Web"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Visual Basic I" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Desenvolvedor de Sistemas e Web"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Visual Basic II" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Informática Master "), (SELECT m.Id FROM modulo m WHERE m.Nome = "CorelDraw X6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Informática Master "), (SELECT m.Id FROM modulo m WHERE m.Nome = "Dreamweaver CS6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Informática Master "), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Informática Master "), (SELECT m.Id FROM modulo m WHERE m.Nome = "Fireworks CS6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Informática Master "), (SELECT m.Id FROM modulo m WHERE m.Nome = "Flash CS6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Informática Master "), (SELECT m.Id FROM modulo m WHERE m.Nome = "Google e Redes Sociais" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Informática Master "), (SELECT m.Id FROM modulo m WHERE m.Nome = "HTML 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Informática Master "), (SELECT m.Id FROM modulo m WHERE m.Nome = "Internet com Oulook 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Informática Master "), (SELECT m.Id FROM modulo m WHERE m.Nome = "Photoshop CS6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Informática Master "), (SELECT m.Id FROM modulo m WHERE m.Nome = "PowePoint 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Informática Master "), (SELECT m.Id FROM modulo m WHERE m.Nome = "Windows 10" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Informática Master "), (SELECT m.Id FROM modulo m WHERE m.Nome = "Word 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Web Designer 2016"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Dreamweaver CS6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Web Designer 2016"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Fireworks CS6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Web Designer 2016"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Flash CS6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Web Designer 2016"), (SELECT m.Id FROM modulo m WHERE m.Nome = "FrontPage 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Web Designer 2016"), (SELECT m.Id FROM modulo m WHERE m.Nome = "HTML 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Web Designer 2016"), (SELECT m.Id FROM modulo m WHERE m.Nome = "PHP" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista Financeiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Administração Financeira 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista Financeiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Escrita Fiscal e Contabilidade 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista Financeiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Atendimento Nota 1000" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista Financeiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Cobrança" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista Financeiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Credito" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista Financeiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Custos" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista Financeiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista Financeiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel Avançado I 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista Financeiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel Avançado II 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista Financeiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Matematica Financeira 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista Financeiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Operador de Caixa 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista Financeiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "PowePoint 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista Financeiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Windows 10" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista Financeiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Word 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor de Marketing e Vendas 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Administração Financeira 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor de Marketing e Vendas 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Propaganda e Marketing 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor de Marketing e Vendas 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Atendimento Nota 1000" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor de Marketing e Vendas 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor de Marketing e Vendas 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel Avançado I 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor de Marketing e Vendas 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel Avançado II 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor de Marketing e Vendas 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Liderança" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor de Marketing e Vendas 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Matematica Financeira 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor de Marketing e Vendas 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "PowePoint 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor de Marketing e Vendas 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Vendas" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor de Marketing e Vendas 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Windows 10" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor de Marketing e Vendas 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Word 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Clínincas e Laboratórios 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Digitação" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Clínincas e Laboratórios 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente Administrativo 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Clínincas e Laboratórios 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Auxiliar Médico" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Clínincas e Laboratórios 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Clínincas e Laboratórios 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Internet com Oulook 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Clínincas e Laboratórios 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "PowePoint 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Clínincas e Laboratórios 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Secretariado 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Clínincas e Laboratórios 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Técnicas de Recepção" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Clínincas e Laboratórios 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Windows 10" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Clínincas e Laboratórios 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Word 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Farmácia 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Digitação" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Farmácia 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Atendente de Farmácia" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Farmácia 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Atendimento Nota 1000" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Farmácia 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Farmácia 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Internet com Oulook 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Farmácia 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Operador de Caixa 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Farmácia 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "PowePoint 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Farmácia 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Técnicas de Recepção" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Farmácia 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Vendas" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Farmácia 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Windows 10" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Atendente de Farmácia 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Word 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Desenvolvedor de Games e Apps"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Desenvolvimento de Aplicativos" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Desenvolvedor de Games e Apps"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Desenvolvimento de Games" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor Administrativo 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Administração Financeira 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor Administrativo 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Departamento Pessoal 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor Administrativo 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Escrita Fiscal e Contabilidade 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor Administrativo 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Propaganda e Marketing 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor Administrativo 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Cobrança" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor Administrativo 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Compras e Estoque" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor Administrativo 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Credito" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor Administrativo 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Custos" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor Administrativo 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor Administrativo 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Liderança" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor Administrativo 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Matematica Financeira 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor Administrativo 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "PowePoint 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor Administrativo 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Secretariado 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor Administrativo 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Windows 10" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Gestor Administrativo 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Word 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Primeiro Emprego"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Digitação" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Primeiro Emprego"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente Administrativo 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Primeiro Emprego"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Administração Financeira 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Primeiro Emprego"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Departamento Pessoal 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Primeiro Emprego"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Escrita Fiscal e Contabilidade 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Primeiro Emprego"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Propaganda e Marketing 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Primeiro Emprego"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Primeiro Emprego"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Internet com Oulook 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Primeiro Emprego"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Matematica Financeira 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Primeiro Emprego"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Operador de Caixa 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Primeiro Emprego"), (SELECT m.Id FROM modulo m WHERE m.Nome = "PowePoint 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Primeiro Emprego"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Secretariado 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Primeiro Emprego"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Windows 10" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Primeiro Emprego"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Word 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Supervisor Hoteleiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente Administrativo 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Supervisor Hoteleiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Departamento Pessoal 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Supervisor Hoteleiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Atendimento Nota 1000" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Supervisor Hoteleiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Hotelaria" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Supervisor Hoteleiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Liderança" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Supervisor Hoteleiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Secretariado 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Supervisor Hoteleiro"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Turismo 2" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Supervisor de Atendimento e CallCenter 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente Administrativo 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Supervisor de Atendimento e CallCenter 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Departamento Pessoal 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Supervisor de Atendimento e CallCenter 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Atendimento Nota 1000" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Supervisor de Atendimento e CallCenter 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Supervisor de Atendimento e CallCenter 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel Avançado I 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Supervisor de Atendimento e CallCenter 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel Avançado II 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Supervisor de Atendimento e CallCenter 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Liderança" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Supervisor de Atendimento e CallCenter 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Telemarketing Mod 1" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Supervisor de Atendimento e CallCenter 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Telemarketing Mod 2" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Supervisor de Atendimento e CallCenter 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Vendas" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Supervisor de Atendimento e CallCenter 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Word 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de Recursos Humanos 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente Administrativo 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de Recursos Humanos 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Administração Financeira 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de Recursos Humanos 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Departamento Pessoal 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de Recursos Humanos 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Escrita Fiscal e Contabilidade 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de Recursos Humanos 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Atendimento Nota 1000" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de Recursos Humanos 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de Recursos Humanos 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Liderança" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de Recursos Humanos 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "PowePoint 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de Recursos Humanos 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Windows 10" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Analista de Recursos Humanos 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Word 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Secretariado Executivo"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Digitação" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Secretariado Executivo"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente Administrativo 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Secretariado Executivo"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Atendimento Nota 1000" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Secretariado Executivo"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Secretariado Executivo"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel Avançado I 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Secretariado Executivo"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel Avançado II 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Secretariado Executivo"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Internet com Oulook 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Secretariado Executivo"), (SELECT m.Id FROM modulo m WHERE m.Nome = "PowePoint 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Secretariado Executivo"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Secretariado 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Secretariado Executivo"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Windows 10" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Secretariado Executivo"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Word 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Designer Gráfico 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "CorelDraw X6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Designer Gráfico 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Edição de Video Adobe Premiere Pro CS6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Designer Gráfico 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Fireworks CS6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Designer Gráfico 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Indesign CS6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Designer Gráfico 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Photoshop CS6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Designer Gráfico 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "PowePoint 2019" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Operador de Caixa 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente Administrativo 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Operador de Caixa 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Atendimento Nota 1000" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Operador de Caixa 2017"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Operador de Caixa 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Desenvolvedor de games"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Desenvolvimento de Games" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Desenvolvedor de aplicativos"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Desenvolvimento de Aplicativos" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Youtuber"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Edição de Video Adobe Premiere Pro CS6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Youtuber"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Youtuber" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Rotinas Administrativas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente Administrativo 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Rotinas Administrativas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Administração Financeira 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Rotinas Administrativas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Departamento Pessoal 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Rotinas Administrativas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Escrita Fiscal e Contabilidade 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Rotinas Administrativas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Assistente de Propaganda e Marketing 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Rotinas Administrativas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Liderança" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Rotinas Administrativas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Matematica Financeira 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Rotinas Administrativas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Operador de Caixa 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Rotinas Administrativas"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Secretariado 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Excel Avançado 2013"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Excel Avançado 2013"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel Avançado I 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Excel Avançado 2013"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Excel Avançado II 2013" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Preparatório para ENEM"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Preparatório ENEM 2017" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Desenvolvimento de Aplicativos Avançados"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Desenvolvimento de Aplicativos Avançado" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Desenvolvimento de Games Avançado"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Desenvolvimento de Games Avançado" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "English Course Book"), (SELECT m.Id FROM modulo m WHERE m.Nome = "English Course Book 1" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "English Course Book"), (SELECT m.Id FROM modulo m WHERE m.Nome = "English Course Book 2" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "English Course Book"), (SELECT m.Id FROM modulo m WHERE m.Nome = "English Course Book 3" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "English Course Book"), (SELECT m.Id FROM modulo m WHERE m.Nome = "English Course Book 4" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Robótica Inventor"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Robótica I -Mecânica e Eletrônica" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Robótica Inventor"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Robótica II - Lógica de Programação" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Robótica Inventor"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Robótica III - Automação" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Robótica Inventor"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Robótica IV - Competição" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Robótica Inventor"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Robótica V - Arduíno com IOT" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Designer Gráfico e Digital"), (SELECT m.Id FROM modulo m WHERE m.Nome = "CorelDraw X6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Designer Gráfico e Digital"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Edição de Video Adobe Premiere Pro CS6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Designer Gráfico e Digital"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Fireworks CS6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Designer Gráfico e Digital"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Flash CS6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Designer Gráfico e Digital"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Indesign CS6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Designer Gráfico e Digital"), (SELECT m.Id FROM modulo m WHERE m.Nome = "Photoshop CS6" and m.Modalidade = 0)),
						((SELECT c.Id FROM curso c WHERE c.Nome = "Designer Gráfico e Digital"), (SELECT m.Id FROM modulo m WHERE m.Nome = "PowePoint 2019" and m.Modalidade = 0));

INSERT INTO escolaridade (criado_em, atualizado_em, descricao)
	   			VALUES  ((select now()), (select now()), "Ensino Fundamental"),
						((select now()), (select now()), "Ensino Médio"),
						((select now()), (select now()), "Ensino Superior"),
						((select now()), (select now()), "Pós-Graduação"),
						((select now()), (select now()), "Mestrado"),
						((select now()), (select now()), "Phd/Doutorado"),
                        ((select now()), (select now()), "Ensino Fundamental - Incompleto"),
						((select now()), (select now()), "Ensino Médio - Incompleto"),
						((select now()), (select now()), "Ensino Superior - Incompleto"),
						((select now()), (select now()), "Pós-Graduação - Incompleto"),
						((select now()), (select now()), "Mestrado - Incompleto"),
						((select now()), (select now()), "Phd/Doutorado - Incompleto"),
						((select now()), (select now()), "Ensino Infantil");

INSERT INTO profissao (criado_em, atualizado_em, descricao)
	   			VALUES  ((select now()), (select now()), "Empresário"),
						((select now()), (select now()), "Estudante"),
						((select now()), (select now()), "Analista de Sistemas"),
						((select now()), (select now()), "Programador(a)"),
						((select now()), (select now()), "Engenheiro(a)"),
						((select now()), (select now()), "Advogado(a)"),
						((select now()), (select now()), "Médico(a)"),
						((select now()), (select now()), "Dentista"),
						((select now()), (select now()), "Administrador(a)"),
						((select now()), (select now()), "Auxiliar de Escritório"),
						((select now()), (select now()), "Contador(a)"),
						((select now()), (select now()), "Professor(a)"),
						((select now()), (select now()), "Dono(a) de Casa"),
						((select now()), (select now()), "Procurando Emprego"),
						((select now()), (select now()), "Aposentado(a)"),
						((select now()), (select now()), "Secretário(a)"),
						((select now()), (select now()), "Outra"),
						((select now()), (select now()), "Gerente"),
						((select now()), (select now()), "Profissional Liberal"),
						((select now()), (select now()), "Auxiliar Administrativo"),
						((select now()), (select now()), "Diretor(a)"),
						((select now()), (select now()), "Autônomo"),
						((select now()), (select now()), "Funcionário Público"),
						((select now()), (select now()), "Consultor(a)"),
						((select now()), (select now()), "Nenhuma"),
						((select now()), (select now()), "Vendedor(a)"),
						((select now()), (select now()), "Enfermeiro(a)"),
						((select now()), (select now()), "Cabelereiro(a)"),
						((select now()), (select now()), "Ajudante de Cozinheiro(a)"),
						((select now()), (select now()), "Ajudante de Maquinista"),
						((select now()), (select now()), "Arquiteto(a)"),
						((select now()), (select now()), "Barbeiro"),
						((select now()), (select now()), "Contramestre(m/f)"),
						((select now()), (select now()), "Cozinheiro(a)"),
						((select now()), (select now()), "Educador"),
						((select now()), (select now()), "Eletricista"),
						((select now()), (select now()), "Parteiro(a)"),
						((select now()), (select now()), "Eletricista(m/f)"),
						((select now()), (select now()), "Farmacêutico(a)"),
						((select now()), (select now()), "Fisioterapeuta(m/f)"),
						((select now()), (select now()), "Governanta"),
						((select now()), (select now()), "Instalador(a)"),
						((select now()), (select now()), "Instrutor(a)"),
						((select now()), (select now()), "Maicure/Pedicure(m/f)"),
						((select now()), (select now()), "Maquinista"),
						((select now()), (select now()), "Marinheiro(a)"),
						((select now()), (select now()), "Massagista(m/f)"),
						((select now()), (select now()), "Mecânico(a)"),
						((select now()), (select now()), "Motorista(m/a)"),
						((select now()), (select now()), "Pescador(a)"),
						((select now()), (select now()), "Porteiro(a)"),
						((select now()), (select now()), "Professor(a)"),
						((select now()), (select now()), "Psicólogo(a)"),
						((select now()), (select now()), "Recepcionista(m/f)"),
						((select now()), (select now()), "Soldador(a)"),
						((select now()), (select now()), "Técnico(a)"),
						((select now()), (select now()), "Terapeuta(m/f)"),
						((select now()), (select now()), "Terapeuta Ocupacional(m/f)"),
						((select now()), (select now()), "Veterinário(a)"),
						((select now()), (select now()), "Atendente"),
						((select now()), (select now()), "Ajudante Geral"),
						((select now()), (select now()), "Operador de Caixa"),
						((select now()), (select now()), "Balconista"),
						((select now()), (select now()), "Pedreiro"),
						((select now()), (select now()), "Agricultor");


INSERT INTO endereco 
 		  (criado_em, atualizado_em, bairro, cep, cidade, estado, logradouro, complemento, numero)
	VALUES((select now()), (select now()), "Centro",
		   "58300-130",
		   "Santa Rita",
		   "PB",
		   "Praça Getúlio Vargas",
		   "N/A",
		    "94");


INSERT INTO aluno 
 		  (criado_em, atualizado_em, cpf, data_de_nascimento, email, estado_civil, nome, orgao_rg, rg, sexo,
 		   telefone1, endereco_id, escolaridade_id, profissao_id)
	VALUES((select now()), 
	       (select now()), 
	       "04282629452",
		   "1983-02-07",
		   "luizflorentino@gmail.com",
		   1,
		   "Luiz Augusto Filho",
		   "SSP-PB",
		    "2534004",
		   1,
		   "83999858233",
		   1,
		   1,
		   1);


INSERT INTO responsavel 
 		  (criado_em, atualizado_em, cpf, data_de_nascimento, email, estado_civil, nome, orgao_rg, rg, sexo,
 		   telefone1, endereco_id, escolaridade_id, profissao_id)
	VALUES((select now()), 
	       (select now()), 
	       "04282629452",
		   "1983-02-07",
		   "luizflorentino@gmail.com",
		   1,
		   "Luiz Augusto Filho",
		   "SSP-PB",
		    "2534004",
		   1,
		   "83999858233",
		   1,
		   1,
		   1);


INSERT INTO prestador_de_servico 
          (criado_em, atualizado_em, cnpj , data_abertura, email, inscr, nome_fantasia, razao_social, telefones, endereco_id)
    VALUES((select now()), (select now()), "31.049.075/0001-35", 
          "2016-08-26",
          "LUIZ AUGUSTO BEZERRA FLORENTINO FILHO",
          "PREPARA SANTA RITA",
          "santarita@prepara.com.br",
          "(83) 3217-2008",
          "ISENTO",
          1);
